#!/bin/sh

[ -f "$1" ] || exit 0;

# yarn commitlint --edit "$1" || exit 1;
project_dir="$(dirname "$0")/..";
if ! test -d "${project_dir}/node_modules"; then
	project_dir="${project_dir}/..";
	test -d "${project_dir}/node_modules" || exit 0;
fi

commitlint="${project_dir}/node_modules/.bin/commitlint";
test -x "$commitlint" || exit 0;
"$commitlint" --edit "$1";
